### PR TITLE
Switching to phpbench/phpbench based benchmarks

### PR DESCRIPTION
**Pull request by michalbundyra**
Hm... `MultipleEventMultipleLocalAndSharedListenerBench::benchTrigger` is very slow...

/cc @Ocramius

### CODE REVIEW

**Comment by Ocramius** [comment]
Overall looks good, but we need to also run them at least once in CI to make sure the benchmarks are maintained.

Also make sure to run this with at least `--revs=2` and `--iterations=2` (or higher) to ensure tests are repeatable. A `--warmup` would also be nice.

**Comment by michalbundyra** [comment]
@Ocramius 
> Also make sure to run this with at least --revs=2 and --iterations=2 (or higher) to ensure tests are repeatable. A --warmup would also be nice.

So you'd like to remove annotations from `bench*` methods and add these params on run command?
Right now I have on all `bench*` methods:
```php
/**
 * @Revs(1000)
 * @Iterations(20)
 */
```

I've done it the same way as it is done in servicemanager, and there we don't benchmarks in Travis CI, but maybe will be good to add it there as well.

**Comment by Ocramius** [comment]
> we don't benchmarks in Travis CI, but maybe will be good to add it there as well.

The reason is to just make sure the benchmarks still run and are stable. The performance on travis is not really important.

If all tests already have >1 revs/iterations then we're fine.

**Comment by michalbundyra** [comment]
@Ocramius I've added running benchmarks on travis. If performance there is not important set command line params which overrides annotations. Is it ok?

**Review by Ocramius — APPROVED** [review]
LGTM 👍

**Pull request merged**
