### PR TITLE
1 byte less per attached event

### PR DESCRIPTION
**Pull request by marc-mabe**
Store priority as array key as `"<prio>."` instead of `"<prio>.0"` as:
- it also doesn't get converted to int 
- it is a compatible float format

### CODE REVIEW

**Comment by marc-mabe** [comment]
Is it really required to store the priority as a string array key?

**Comment by nuxwin** [comment]
There is maybe a valuable reason to store as 1.0 instead of 1. (think of float). At least, from a pure synthetical  point of view, 1. seem really strange...

**Comment by weierophinney** [comment]
Yes; due to the fact we're using array_merge, integer and float keys get
overwritten.

**Comment by marc-mabe** [comment]
@weierophinney shouldn't array_replace[_recursive] solve the issue?

**Comment by weierophinney** [comment]
@marc-mabe No, it does not; each messes with integer and float keys, which had often unexpected and unwanted results (we even saw test failures). That code really _must_ stay the way it is.

**Comment by weierophinney** [comment]
@marc-mabe What real benefit will this patch provide? It feels like it'd be less explicit than we currently have, for very little resource consumption savings. Have you done any benchmarks that can demonstrate otherwise?

**Comment by weierophinney** [comment]
Closing in favor of #17.

**Pull request closed without merging**
