### PR TITLE
EventManager unit tests

### PR DESCRIPTION
**Pull request by rms230**
This pull request increases the code coverage of the module, it also fixes a bug in FilterIterator when trying to extract from an empty heap.

### CODE REVIEW

**Comment by Martin-P** [comment]
> it also fixes a bug in FilterIterator when trying to extract from an empty heap.

I think it is better to split this PR into:
- 1 PR for improved code coverage
- 1 PR for fixing the bug you mentioned

Mixing them into one PR creates lack of clarity.

**Comment by weierophinney** [comment]
I disagree; if the fix was made due to expanding the unit tests, it makes
absolute sense to keep it in the same patch.

**Comment by Martin-P** [comment]
@weierophinney What if the specific tests for the bug are wrong and code was changed to make the tests pass? Because it is unclear which tests are created specifically for the bug fix, it is unclear if all angles are covered. Looking at `FilterIteratorTest` I can already confirm not all code changes are covered (test for `$chain instanceof FilterIterator` part is missing).

Furthermore only `FilterIterator::next()` is covered in `FilterIteratorTest` and all other methods of `FilterIterator` are not tested at all. This indicates the fix was not created by expanding tests, because in that case more methods than only `FilterIterator::next()` would be covered.

**Edit**: The funny thing is we would not even have this discussion if the PR was clear :wink:

**Comment by rms230** [comment]
My apologies for not adding more tests in the FilterIteratorTest.

The reason behind this was because the code was covered elsewhere, however if this is required then I'll make sure to do that for future pull requests.

**Comment by Martin-P** [comment]
@rms230 At this moment certain angles are not covered at all with the introduction of your new code which can create unwanted side effects which could have been prevented with the correct unit tests.

**Pull request closed without merging**
