### PR TITLE
Replace array_key_exists() with isset()

### PR DESCRIPTION
**Pull request by piowin**
For better performance and better logic in the code isset() is more appropriate.
See https://github.com/zendframework/zf2/issues/7663

### CODE REVIEW

**Comment by Ocramius** [comment]
From a quick skim through the code, I can see that nothing denies an identifier from being `null`. If `null` is not a valid identifier (/cc @weierophinney), then we should probably make sure it isn't added to the identifiers during `setIdentifiers` (exception thrown), or else this patch may introduce subtle BC breaks

**Comment by piowin** [comment]
But `$identifiers` property from the `EventManager` class is not the same as `$identifiers` property from  the `SharedEventManager` class. In the `SharedEventManager` class $identifiers is an array of `EventManager` instances where keys are strings (or integers) which are used to pulled shared signals within an `EventManager` instace. Thus an element of `SharedEventManager::$indentifier` array can be only an `EventManager` instance (`SharedEventManager::attach()` creates it, and `SharedEventManager::clearListeners()` unsets if we want). But even if an element of this array would be `null`, then an expression like `$this->identifiers[$id]->getListeners($event)` would cause an error. Yes, there is a question: can `EventManager::$indetifiers` array contain null? But in my opinion this question doesn't affect my PR.

**Comment by Ocramius** [comment]
@peterr that's actually the question to answer to, before applying this patch ;-)

**Comment by weierophinney** [comment]
I'm closing this for a few reasons.

First, the internals of zend-eventmanager changed dramatically in version 3. While we still have an `array_key_exists()` in place, we have also demonstrated huge performance gains; a quick benchmark I did showed essentially no change in performance when changing that to an `isset()` call.

Second, while I do not expect that an identifier would be `null`, the _value_ itself _could_ be, which would make `isset()` fail. As @Ocramius noted, this would be a very subtle BC break.

Third, the patch was done against the `legacy` branch. That branch only existed to ensure that existing sha1s from prior to a change in our repository structures was made would exist. The official branches on this repository, as noted in the `CONTRIBUTING.md`, are master, develop, and release-2.6. We will only be applying security patches to the 2.6 releases at this time.

**Pull request closed without merging**
